modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
[[mods]]
modId="drpgpc"
version="1.19.3-1.0.4"
displayName="DivineRPG Processing Compat"
logoFile="drpgpc.png"
credits="Scalar Team"
authors="Lemon_Juiced"


description='''
Tech Mod Compatability For Divine RPG.

This mod allows Divine RPG ores to be processed like ores in any tech mod.

Currently Supports:
- Applied Energistics 2
- Simple Grinder

Has Supported:
- Create (1.19.2)
- Factorium (1.19.2)
- Immersive Engineering (1.19.2)
- Integrated Dynamics (1.19.2)
- Mekanism (1.19.2)
- Plain Grinder (1.19.2)
- Stone Grinder (1.19.2)
- Thermal Series (1.19.2)
'''

[[dependencies.drpgpc]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.drpgpc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"

# DivineRPG Mandatory Dependency
[[dependencies.drpgpc]]
    modId="divinerpg"
    mandatory=true
    versionRange="[1.9.7,)"
    ordering="NONE"
    side="BOTH"

# Applied Energistics 2 Optional Dependency
[[dependencies.drpgpc]]
    modId="ae2"
    mandatory=false
    versionRange="[12.9.2,)"
    ordering="BEFORE"
    side="BOTH"

# Simple Grinder Optional Dependency
[[dependencies.drpgpc]]
    modId="simplegrinder"
    mandatory=false
    versionRange="[1.0,)"
    ordering="BEFORE"
    side="BOTH"